Fix #13 by solving the shotgun/OCP violation with a plugin/strategy.

diff --git a/bin/aceunit b/bin/aceunit
--- a/bin/aceunit
+++ b/bin/aceunit
@@ -3,6 +3,12 @@
 tool=objdump
 name=fixtures
 
+declare -A tools
+
+for ac in $(realpath -m $0/../../share/aceunit)/*.ac ; do
+    source $ac
+done
+
 usage() {
     echo "Usage: $0 [-h] [-p PATTERN] [-t TOOL] OBJECT_FILE..." 1>&2
 }
@@ -12,12 +18,11 @@ version() {
 }
 
 setType() {
-    case "$1" in
-    objdump) tool=objdump ;;
-    nm) tool=nm ;;
-    readelf) tool=readelf ;;
-    *) echo "$0: error: unsupported symbol table tool '$1'" >&2 ; exit 1 ;;
-    esac
+    if [[ -n "${tools[$1]}" ]] ; then
+        tool=$1
+    else
+        echo "$0: error: unsupported symbol table tool '$1'" >&2 ; exit 1
+    fi
 }
 
 help() {
@@ -39,7 +44,7 @@ Options:
               Example: -s _ to strip a leading underscore from the symbol names.
   -t TOOL     Use TOOL for displaying the symbol table.
               Defaults to objdump.
-              Built-in alternatives: nm, readelf.
+              Supported tools: ${!tools[@]}.
   -v          Print version information and stop.
 
 Examples:
@@ -58,12 +63,11 @@ function getSymbols() {
         echo "$binary: File not found." 1>&2
         exit 2
     fi
-    case "${tool}" in
-    objdump) $binary -t "$1" | grep -E ' g     [F ] [^	 ]+[	 ]+' | sed -e 's/.* '$strip'//' | grep '^\('$2$3'\)' ;;
-    nm)      $binary    "$1" | grep -E ' T '                         | sed -e 's/.* '$strip'//' | grep '^\('$2$3'\)' ;;
-    readelf) $binary -s "$1" | grep -E ' FUNC    GLOBAL DEFAULT '    | sed -e 's/.* '$strip'//' | grep '^\('$2$3'\)' ;;
-    *) echo "$0: internal error: Unsupported tool ${tool}" 1>&2 ; exit 2 ;;
-    esac
+    if [[ $(LC_ALL=C type -t getSymbols_${tool}) == function ]] ; then
+        getSymbols_${tool} $1 $2 $3
+    else
+        echo "$0: internal error: Unsupported tool ${tool}" 1>&2 ; exit 2
+    fi
 }
 
 prefix=
